"""device_locations

Revision ID: 3bae22668b71
Revises: r8g9h0i1j2k3
Create Date: 2026-05-19 00:10:38.960488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bae22668b71'
down_revision: Union[str, Sequence[str], None] = 'r8g9h0i1j2k3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_locations',
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('update_interval', sa.Integer(), nullable=False),
    sa.Column('refresh_requested', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.drop_index(op.f('ix_website_services_slug'), table_name='website_services')
    op.drop_table('website_services')
    op.drop_table('website_members')
    op.drop_table('website_contacts')
    op.drop_index(op.f('ix_website_settings_key'), table_name='website_settings')
    op.drop_table('website_settings')
    op.drop_table('piezas')
    op.alter_column('catalogo_productos', 'es_personalizable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_catalogo_productos_slug'), table_name='catalogo_productos')
    op.create_unique_constraint(None, 'catalogo_productos', ['slug'])
    op.drop_index(op.f('ix_page_visits_visited_at'), table_name='page_visits')
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_page_visits_visited_at'), 'page_visits', ['visited_at'], unique=False)
    op.drop_constraint(None, 'catalogo_productos', type_='unique')
    op.create_index(op.f('ix_catalogo_productos_slug'), 'catalogo_productos', ['slug'], unique=True)
    op.alter_column('catalogo_productos', 'es_personalizable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('piezas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('fotos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('precios', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('monto_pagado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('persona', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), server_default=sa.text("'venta_general'::character varying"), autoincrement=False, nullable=False),
    sa.Column('fecha_encargo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fecha_impresion', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fecha_entrega', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fecha_pago', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('filamento', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tiempo_impresion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sincronizado_sodigic', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('archivos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pagos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('piezas_pkey'))
    )
    op.create_table('website_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('website_settings_pkey'))
    )
    op.create_index(op.f('ix_website_settings_key'), 'website_settings', ['key'], unique=True)
    op.create_table('website_contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contact_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('website_contacts_pkey'))
    )
    op.create_table('website_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('github_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('website_members_pkey'))
    )
    op.create_table('website_services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=100), server_default=sa.text("'code'::character varying"), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), server_default=sa.text("'general'::character varying"), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('long_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_urls', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('website_services_pkey')),
    sa.UniqueConstraint('slug', name=op.f('website_services_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_website_services_slug'), 'website_services', ['slug'], unique=True)
    op.drop_table('device_locations')
    # ### end Alembic commands ###
