"""add title flags to chat_sessions

Revision ID: 5877b7f8a578
Revises: 2fe22e7bb824
Create Date: 2026-02-26 23:38:06.897442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5877b7f8a578'
down_revision: Union[str, Sequence[str], None] = '2fe22e7bb824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_title_auto_generated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'is_title_auto_generated')
    # ### end Alembic commands ###
